import { StyleSheet } from "react-native";
import { MD3Theme } from "react-native-paper";

export const getStyles = (theme: MD3Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      flex: 1,
      paddingHorizontal: "4%",
      paddingBottom: 16,
    },
    viewModeChipsRow: {
      flexDirection: "row",
      gap: 8,
      marginTop: 12,
      marginBottom: 10,
      backgroundColor: theme.colors.elevation.level2,
      borderRadius: 12,
      padding: 4,
    },
    viewModeChip: {
      flex: 1,
      height: 34,
      borderRadius: 8,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    viewModeChipActive: {
      backgroundColor: theme.colors.primaryContainer,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.16,
      shadowRadius: 2,
      elevation: 2,
    },
    viewModeChipInactive: {
      backgroundColor: "transparent",
    },
    altViewControls: {
      gap: 10,
      marginBottom: 10,
    },
    teacherChipsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 2,
      paddingHorizontal: 1,
    },
    teacherChip: {
      height: 34,
      borderRadius: 17,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
      maxWidth: 190,
    },
    sectionBlock: {
      marginBottom: 2,
    },
    sectionAccordionHeader: {
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 2,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.outlineVariant,
    },
    sectionHeaderContent: {
      gap: 2,
      flexShrink: 1,
    },
    sectionFilesRow: {
      gap: 8,
      paddingHorizontal: 1,
      paddingBottom: 2,
    },
    sectionFilesList: {
      gap: 8,
      paddingHorizontal: 1,
      paddingTop: 8,
      paddingBottom: 12,
    },
    archivoCardWrapper: {
      width: "100%",
    },
    archivoCard: {
      width: "100%",
      elevation: 1,
      borderRadius: 12,
      overflow: "hidden",
      position: "relative",
    },
    archivoRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 9,
      gap: 10,
    },
    archivoThumb: {
      width: 42,
      height: 42,
      borderRadius: 12,
      overflow: "hidden",
      backgroundColor: theme.colors.surfaceVariant,
    },
    archivoThumbImage: {
      width: "100%",
      height: "100%",
    },
    iconFallbackContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    archivoMeta: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    archivoTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    archivoTitle: {
      flex: 1,
      fontWeight: "600",
      color: theme.colors.onSurface,
    },
    archivoSubtitle: {
      color: theme.colors.onSurfaceVariant,
      opacity: 0.85,
      fontSize: 11,
    },
    openingProgressBar: {
      marginTop: 6,
      height: 3,
      borderRadius: 999,
      backgroundColor: theme.colors.surfaceVariant,
    },
    downloadingProgressBar: {
      marginTop: 6,
      height: 3,
      borderRadius: 999,
      backgroundColor: theme.colors.surfaceVariant,
    },
    archivoTrailing: {
      marginRight: -6,
    },
    sectionFileCard: {
      width: "100%",
      borderRadius: 12,
      overflow: "hidden",
    },
    sectionFileRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    sectionFileThumb: {
      width: 42,
      height: 42,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    sectionFileMeta: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    sectionFileTitle: {
      color: theme.colors.onSurface,
      fontWeight: "600",
    },
    sectionFileSubtitle: {
      fontSize: 11,
      opacity: 0.85,
    },
    sectionFileTrailing: {
      marginRight: -6,
    },
    sectionEmpty: {
      paddingHorizontal: 4,
      paddingTop: 8,
      paddingBottom: 12,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
      paddingHorizontal: 2,
    },
    sectionTitle: {
      fontWeight: "700",
      color: theme.colors.onSurface,
    },
    card: {
      borderRadius: 16,
      marginBottom: 12,
      overflow: "hidden",
    },
    cardContent: {
      paddingVertical: 16,
      gap: 12,
    },
    topRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    infoBlock: {
      flex: 1,
      gap: 2,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    avatarContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    autorNombre: {
      fontWeight: "600",
      color: theme.colors.onSurface,
    },
    fecha: {
      opacity: 0.7,
      color: theme.colors.onSurface,
    },
    titulo: {
      fontWeight: "bold",
      marginBottom: 8,
      color: theme.colors.onSurface,
    },
    descripcion: {
      opacity: 0.8,
      marginBottom: 12,
      color: theme.colors.onSurface,
    },
    statsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flexShrink: 1,
      flexWrap: "nowrap",
      minWidth: 0,
    },
    statsRowWithDate: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    statItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      flexShrink: 0,
    },
    fileTypesRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      flexWrap: "wrap",
      marginTop: 2,
    },
    fileTypeTag: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 12,
      gap: 4,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 80,
    },
    emptyText: {
      textAlign: "center",
      opacity: 0.7,
      marginTop: 8,
      color: theme.colors.onBackground,
    },
    emptySubtext: {
      textAlign: "center",
      opacity: 0.5,
      marginTop: 4,
      color: theme.colors.onBackground,
    },
    fab: {
      position: "absolute",
      marginHorizontal: "4%",
      marginVertical: 16,
      right: 0,
      bottom: 0,
      backgroundColor: theme.colors.primaryContainer,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 12,
      backgroundColor: theme.colors.background,
      position: "relative",
    },
    searchbarWrapper: {
      flex: 1,
    },
    filtroContainer: {
      position: "relative",
      marginLeft: 2,
    },
    filtroButton: {
      backgroundColor: theme.colors.background,
      borderRadius: 12,
      zIndex: 11,
      borderWidth: 0,
    },
    filtroMenu: {
      position: "absolute",
      top: "100%",
      right: 0,
      backgroundColor: theme.colors.background,
      borderRadius: 12,
      minWidth: 160,
      zIndex: 100,
      borderWidth: 1,
      borderColor: theme.colors.outlineVariant || "#e0e0e0",
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 8,
    },
    filtroRipple: {
      borderRadius: 0,
    },
    filtroItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      paddingHorizontal: 18,
    },
    filtroItemActive: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      paddingHorizontal: 18,
      backgroundColor: theme.colors.secondaryContainer + "22",
    },
    filtroText: {
      fontSize: 15,
      fontWeight: "400",
      color: theme.colors.onBackground,
    },
    filtroTextActive: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.colors.onBackground,
    },
    actionButton: {
      borderRadius: 16,
      overflow: "hidden",
    },
  });

export default getStyles;
